ALTER TABLE channels
  ADD COLUMN description VARCHAR(500),
  ADD COLUMN archived_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE messages
  ADD COLUMN edited_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN deleted_at TIMESTAMP WITH TIME ZONE;
